"""Recommendation — a suggested next action generated by the Decision Engine.

Lifecycle (STATE_MACHINES.md section 6, approved Resolution 4):
Generated -> Pending -> Accepted / Rejected / Expired; Accepted -> Consumed.

Rules (BUSINESS_RULES.md - Recommendation Rules):
- Recommendations never modify history.
- Recommendations require user acceptance.
- Rejected Recommendations remain historical evidence (terminal state,
  append-only history — structurally guaranteed here).
- Recommendations expire over time; an expired Recommendation cannot be
  accepted (enforced in ``accept``).
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, ClassVar

from paios.domain.entities.base import Entity
from paios.domain.enums import RecommendationStatus
from paios.domain.errors import (
    DomainValidationError,
    ImmutabilityViolationError,
    RecommendationExpiredError,
)
from paios.domain.state_machines.definitions import RECOMMENDATION_STATE_MACHINE
from paios.domain.state_machines.machine import TransitionHistory, TransitionRecord
from paios.domain.value_objects.identifiers import (
    ProjectId,
    RecommendationId,
    UserId,
)

_DEFAULT_ACTOR = "Scheduler"


@dataclass(eq=False)
class Recommendation(Entity):
    _id_attr: ClassVar[str] = "recommendation_id"

    recommendation_id: RecommendationId
    user_id: UserId
    reason: str
    created_at: datetime
    expires_at: datetime
    related_project_id: ProjectId | None = None
    priority: float | None = None
    expected_benefit: str | None = None
    suggested_timing: datetime | None = None
    confidence_score: float | None = None
    _history: TransitionHistory[RecommendationStatus] = field(
        init=False, repr=False
    )

    def __post_init__(self) -> None:
        if not self.reason.strip():
            raise DomainValidationError("Recommendation requires a reason")
        if self.expires_at <= self.created_at:
            raise DomainValidationError(
                "Recommendation must expire after it was created"
            )
        self._history = TransitionHistory(
            RECOMMENDATION_STATE_MACHINE, RecommendationStatus.GENERATED
        )

    def __setattr__(self, name: str, value: Any) -> None:
        if name == "_history" and "_history" in self.__dict__:
            raise ImmutabilityViolationError(
                "Recommendation transition history cannot be replaced; "
                "rejected Recommendations remain immutable decision evidence"
            )
        super().__setattr__(name, value)

    @property
    def status(self) -> RecommendationStatus:
        return self._history.current_state

    @property
    def transitions(self) -> tuple[TransitionRecord[RecommendationStatus], ...]:
        return self._history.records

    def is_expired(self, at: datetime) -> bool:
        return at >= self.expires_at

    def present(
        self, at: datetime, actor: str = "Runtime"
    ) -> TransitionRecord[RecommendationStatus]:
        return self._history.apply(RecommendationStatus.PENDING, at, actor, None)

    def accept(
        self,
        at: datetime,
        actor: str = _DEFAULT_ACTOR,
        reason: str | None = None,
    ) -> TransitionRecord[RecommendationStatus]:
        """User acceptance, applied by the Scheduler (STATE_MACHINES.md).

        An expired Recommendation cannot be accepted — validity is checked
        against the caller-supplied Current Time before the transition.
        """
        if self.is_expired(at):
            raise RecommendationExpiredError(
                f"Recommendation {self.recommendation_id} expired at "
                f"{self.expires_at.isoformat()} and cannot be accepted"
            )
        return self._history.apply(RecommendationStatus.ACCEPTED, at, actor, reason)

    def reject(
        self,
        at: datetime,
        actor: str = _DEFAULT_ACTOR,
        reason: str | None = None,
    ) -> TransitionRecord[RecommendationStatus]:
        """Rejection is terminal; the Recommendation remains historical evidence."""
        return self._history.apply(RecommendationStatus.REJECTED, at, actor, reason)

    def expire(
        self,
        at: datetime,
        actor: str = _DEFAULT_ACTOR,
        reason: str | None = None,
    ) -> TransitionRecord[RecommendationStatus]:
        """Validity ended — by time, Context, Resources, or changed reality."""
        return self._history.apply(RecommendationStatus.EXPIRED, at, actor, reason)

    def consume(
        self,
        at: datetime,
        actor: str = _DEFAULT_ACTOR,
        reason: str | None = None,
    ) -> TransitionRecord[RecommendationStatus]:
        """The Scheduler incorporated the accepted Recommendation for planning."""
        return self._history.apply(RecommendationStatus.CONSUMED, at, actor, reason)
